PROGRAM Print(INPUT, OUTPUT);
USES 
  DOS;
BEGIN{PRINT}
  WRITELN('Contrnt-Type: text/plain');
  WRITELN;
  WRITELN('REQUEST_METHOD: ', GetEnv('REQUEST_METHOD'));
  WRITELN('QUERYY_STRING: ', GetEnv('QUERY_STRING'));
  WRITELN('CONTENT_LENGHT: ', GetEnv('CONTENT_LENGHT'));
  WRITELN('HTTP_USER_AGENT: ', GetEnv('HTTP_USER_AGENT'));
  WRITELN('REQUST_METHOD: ', GetEnv('HTTP_HOST'))
END.{PRINT}
